### ISSUE TITLE
execfile issue in setup.py

### ISSUE THREAD

**Issue by sunilk-n** [dreamworksanimation/usdmanager#2]
When running the installation "python setup.py install" python is not recognizing the execfile command... instead I had implemented exec(open(<filename>).read()) and it worked with that... Can you please update the issue

**Comment by mds-dwa** [comment]
What version of Python are you using? execfile was removed in Python 3, but this release of usdmanager currently only works in Python 2. It can be updated with some simple changes, which we could potentially add as a new branch, if this is needed.

**Comment by sunilk-n** [comment]
Ohhh thanks... I'm using Python 3.6... And of course Everyone is upgrading to 3.X in future so we will need it for 3.x

**Comment by mds-dwa** [comment]
There's a personal (i.e. currently unsupported/unofficial) python 3 branch available [here](https://github.com/mdsandell/usdmanager/tree/python3). Since code changes are minimal, if python 3 does become a recurring request for this project, we may look into the feasibility of maintaining the current python 2 branches plus some python 3 branches.
